version: '3'  # Assurez-vous d'utiliser la version de Docker Compose appropriée

services:
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin-network

networks:
  zipkin-network:  # Définition du réseau personnalisé
    driver: bridge

